CC = gcc
SRC_FILES = showme.c
OBJ_FILES = *.o
OPTS = -pedantic -Wall -g
EXE = showme

build: $(SRC_FILE)
	$(CC) $(OPTS) -o $(EXE) $(SRC_FILES)

.PHONY: clean

clean:
	rm -f $(EXE) $(OBJ_FILES)       

