CC = gcc
SRC_FILES = ssp.c
OBJ_FILES = *.o
OPTS = -std=c99 -pedantic -Wall -g
EXE = ssp

build: $(SRC_FILE)
	$(CC) $(OPTS) -o $(EXE) $(SRC_FILES)

.PHONY: clean

clean:
	rm -f $(EXE) $(OBJ_FILES)       

